db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=http://rocketchat20180502.xfrocks.com:3000
  links:
    - db:db
  ports:
    - 3000:3000

caddy:
  image: abiosoft/caddy
  links:
    - rocketchat
  volumes:
    - ./Caddyfile:/etc/Caddyfile:ro
    - ./data/runtime/caddy:/root/.caddy
  ports:
    - 80:80
    - 443:443
